# Generated by Django 5.0.4 on 2024-11-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="profile_images/default.jpg",
                upload_to="profile_images/",
                verbose_name="Profile Image",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_owner",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Phone Number"
            ),
        ),
    ]
